import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Variable } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider appearance={{
        layout:{
          logoImageUrl:"/icons/yoom-logo.svg",
          socialButtonsVariant:"iconButton"
        },
        variables: {
          colorText: "white",
          colorPrimary:"#0E78F9",
          colorBackground:"#1c1f2e",
          colorInputText:"white",
          colorInputBackground:"#252a41"
        }
      }} >
        <body className={`${inter.className} bg-dark-2`}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
